### ISSUE TITLE
Keytar not working in Windows

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/gh-notifications-snoozer#107]
> Uncaught Error: A dynamic link library (DLL) initialization routine failed.
> 
> node_modules\keytar\build\Release\keytar.node

![keytar-failure-windows](https://cloud.githubusercontent.com/assets/82317/19421164/ed048f16-93bf-11e6-94aa-3420e9e81aad.png)

**Comment by cheshire137** [comment]
Based on http://stackoverflow.com/questions/36029955/electron-uncaught-error-a-dynamic-link-library-dll-initialization-routine-fai, I need to run `.\node_modules\.bin\electron-rebuild`. However, when I run that, I get:

> gyp ERR! clean error
> gyp ERR! stack Error: EPERM: operation not permitted, unlink 'C:\Users\chesh\Documents\GitHub\gh-notifications-snoozer\node_modules\nslog\build\Release\nslog.node'

This looks like the error described in https://github.com/electron/electron-rebuild/issues/15.

**Comment by cheshire137** [comment]
Thinking I could follow the example in https://github.com/electron/electron-rebuild/issues/15#issuecomment-184664680 and specify exactly the keytar module, I ran `.\node_modules\.bin\electron-rebuild -w keytar -p` but that failed with:

> gyp ERR! build error
> gyp ERR! stack Error: `msbuild` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit

**Comment by cheshire137** [comment]
👋 @lee-dohm, any thoughts on what I might be doing wrong here? Here's what I'm working with in Windows 10:

```
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (gh-notifications-snoozer\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\my_path\\gh-notifications-snoozer\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd gh-notifications-snoozer\node_modules\keytar
gyp ERR! node -v v6.8.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\my_path\\gh-notifications-snoozer\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "keytar" "--runtime=electron" "--target=1.4.3" "--arch=x64"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! keytar@3.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@3.0.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keytar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.
```

```
>which python
/d/Python27/python
```

**Comment by jerone** [comment]
Tried building this on Windows 7 today and having the same result as @cheshire137 for every same step. Hoping someone can come up with a solution.

**Comment by sweatC** [comment]
Hi, @cheshire137 !
I fixed this bug. You need to rebuild native modules is via the _electron-rebuild package_, which handles the manual steps of downloading headers and building native modules:

`npm install --save-dev electron-rebuild`

`.\node_modules\.bin\electron-rebuild.cmd`
