### ISSUE TITLE
ENOENT: no such file or directory, mkdir '/Users/username/Library/Application Support/GHSnooze/extensions

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/gh-notifications-snoozer#113]
@mcolyer experienced this with node 6.8.1 and npm 3.10.10 while running `npm start`:

```
[1]     at Error (native)
[1]     at Object.fs.mkdirSync (fs.js:922:18)
[1]     at getPath (/Users/username/external/gh-notifications-snoozer/node_modules/electron-devtools-installer/dist/utils.js:26:18)
[1]     at Object.<anonymous> (/Users/username/external/gh-notifications-snoozer/node_modules/electron-devtools-installer/dist/index.js:42:59)
[1]     at Module._compile (module.js:556:32)
[1]     at Object.require.extensions.(anonymous function) [as .js] (/Users/username/external/gh-notifications-snoozer/node_modules/electron-compile/lib/require-hook.js:36:14)
[1]     at Module.load (module.js:473:32)
[1]     at tryModuleLoad (module.js:432:12)
[1]     at Function.Module._load (module.js:424:3)
[1]     at Module.require (module.js:483:17)
```

**Comment by cheshire137** [comment]
Running `mkdir /Users/username/Library/Application\ Support/GHSnooze` fixed it, he reports. This may be a directory Redux uses for persisting state, but it seems like it should make the directory for us. He's in macOS Sierra.

**Comment by WillAbides** [comment]
I also ran into this.  I'm on OS X El Capitan
