### ISSUE TITLE
Show errors to user

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/gh-notifications-snoozer#87]
If I use the wrong scope on the GitHub access token, I get an error when the app tries to fetch notifications. This only shows up in the JavaScript console, though, and the user just sees a white screen. We should show the error message to the user so they know to create a new token with the `repo` scope:

![missing-notifications-scope](https://cloud.githubusercontent.com/assets/82317/18898568/13f2b8ae-84f8-11e6-982d-e85ebbb3814a.png)

It would be nice if we had a central way of managing error messages so we could consistently display them to the user throughout the app.

**Comment by s4kh** [comment]
Can you tell me how achieve this scenario?

**Comment by cheshire137** [comment]
Sure! We're already catching errors throughout the app, that's how we're able to see the "failed to get notifications" text in the screenshot above. Everywhere we're catching an error, we're currently just using console.error to display the error in the JavaScript console. This helps developers for debugging, but not the user for knowing what went wrong and how they might fix it.

I think the console.error calls should stay because they're helpful, but in addition to them, we should render the error to the user. The simplest way to do that would be in each component where we have an error we're handling, we should update the component state with an error message when they occur. Then we can have a chunk in the render method that, if the error string is set in the state, we display it.

If something else changes such that the error no longer applies, we should wipe it from the state so that it's no longer displayed. For example, the notifications error in the screenshot can be fixed by the user changing their access token. For some errors that block other things, we would want to do some extra work so that the user isn't blocked. For notifications not loading, we'd want to go ahead and load tasks still after displaying the error message. Both hiding no-longer-applicable errors and loading tasks after notifications fail to load, though, could come in a separate branch. Just displaying the error is an improvement. 

The Bulma CSS library we're using has some notification classes that would be helpful for styling errors.

**Comment by s4kh** [comment]
Can't get the project running. It gives dependency error on eslint version when I run `npm install`. However, I installed every modules by downgrading the version numbers in the package.json.

`npm start` gives following:

```
Error: Cannot find module 'babel-runtime/core-js/object/assign'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (D:\self-projects\gh-notifications-        snoozer\node_modules\electron-prebuilt-compile\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\self-projects\gh-notifications-snoozer\node_modules\electron-prebuilt-compile\node_modules\electron-compile\lib\index.js:3:15)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

**Comment by cheshire137** [comment]
Can you share your node and npm versions? The app was developed with npm version 3.10.3 and node version 6.3.1, mainly in macOS but also tested in Windows 10. You may need to upgrade your npm and node if they're not versions 3.x and 6.x.

**Comment by s4kh** [comment]
Thanks for the quick response. Updated my npm to 3.10.3, node to 6.7.0. Now, when I run `npm install`

```
+-- UNMET PEER DEPENDENCY eslint@3.6.1
| +-- file-entry-cache@2.0.0
| +-- natural-compare@1.4.0
| `-- strip-bom@3.0.0
`-- UNMET PEER DEPENDENCY eslint-plugin-jsx-a11y@2.2.2

npm WARN eslint-config-airbnb@9.0.1 requires a peer of eslint@^2.9.0 but none was installed.
npm WARN eslint-config-airbnb@9.0.1 requires a peer of eslint-plugin-jsx-a11y@^1.2.0 but none     was installed.
```

When I install eslint@^2.9.0,  eslint-plugin-jsx-a11y@^1.2.0 by downgrading version numbers it still gives me the `Error: Cannot find module 'babel-runtime/core-js/object/assign'`

**Comment by cheshire137** [comment]
I think you're good even with those warnings. I wouldn't worry about getting to eslint ^2.9.0. I think I get those same "unmet peer dependency" warnings and it works fine. eslint is just the tool used for style checking to keep the code looking consistent.

**Comment by s4kh** [comment]
The main thing is can't run the app cause of 

> Error: Cannot find module 'babel-runtime/core-js/object/assign'
>     at Module._resolveFilename (module.js:455:15)
>     at Function.Module._resolveFilename (D:\self-projects\gh-notifications-        snoozer\node_modules\electron-prebuilt-compile\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
>     at Function.Module._load (module.js:403:25)
>     at Module.require (module.js:483:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (D:\self-projects\gh-notifications-snoozer\node_modules\electron-prebuilt-compile\node_modules\electron-compile\lib\index.js:3:15)
>     at Module._compile (module.js:556:32)
>     at Object.Module._extensions..js (module.js:565:10)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)

**Comment by s4kh** [comment]
Solution: `npm install babel-runtime regenerator-runtime` . Finally got it running. @cheshire137 Thanks for the quick responses.

**Comment by cheshire137** [comment]
Oh good! I wonder if we should add `babel-runtime` and `regenerator-runtime` to the devDependencies section of the top-level package.json.

Are you in Windows, based on the `D:\` in your paths? I didn't have to install those separately in Windows 10 when I first ran the app. I just installed v6.7.0 for Windows from https://nodejs.org/en/download/current/ and `npm install` ran successfully for me, then the app ran successfully.

**Comment by s4kh** [comment]
After `npm start` on the electron window it should show something, right? Currently, only seeing a blank. Screenshot:
![capture](https://cloud.githubusercontent.com/assets/15072209/18979566/b584b322-86fe-11e6-8851-a02065df08f1.PNG)

Sad.

**Comment by cheshire137** [comment]
You came here to fix one bug, instead you're finding all our others. 😀 

The lack of errors in the console is odd. What shows up in the console tab?

**Comment by s4kh** [comment]
Nothing. First, it was showing: 
`Uncaught SyntaxError: Unexpected token < index.jsx:18`.  
Changed 

`<script type="application/javascript" src="index.jsx"></script>` script type to `text/jsx`. 
And now it shows nothing even in cmd.

**Comment by cheshire137** [comment]
It's like stuff isn't compiling. If you run `NODE_ENV=test npm test`, do tests pass?

**Comment by s4kh** [comment]
`Failed at the gh-notifications-snoozer@0.0.1 style script 'eslint -c .eslintrc *.js scripts/* src/*.js src/**/*.jsx test/**/*.js'.`

**Comment by cheshire137** [comment]
Try running just the unit tests via `env NODE_ENV=test npm run unit-tests`:

![unit-tests-snoozer](https://cloud.githubusercontent.com/assets/82317/18981223/c837af54-86a1-11e6-94d6-4d660bf4d85f.png)

**Comment by s4kh** [comment]
![capture](https://cloud.githubusercontent.com/assets/15072209/18981330/bf30d93a-870f-11e6-927e-cdd26e9c5fe6.PNG)
![capture2](https://cloud.githubusercontent.com/assets/15072209/18981336/d1bc40bc-870f-11e6-913a-c624f456d078.PNG)

**Comment by cheshire137** [comment]
Ughh so it's weird you get failures at all, let alone so many of them. I get 0 failures in Windows. Can you share the output of `node -v` and `npm -v`?

**Comment by s4kh** [comment]
node: 6.7.0 npm: 3.10.3

**Comment by s4kh** [comment]
So yeah, I cloned the project to my ubuntu laptop and it works with `npm install && npm start`.

**Comment by cheshire137** [comment]
Well I'm glad it works for you in Ubuntu, but I'm sorry it wasn't working in Windows! I'm not sure what's up if you're using the same versions of node and npm I am in Windows.
